version: '3.8'

services:
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/orders
    depends_on:
      - db
    networks:
      - quickdelivery-network

  logistics-service:
    build: ./logistics-service
    container_name: logistics-service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/logistics
    depends_on:
      - db
    networks:
      - quickdelivery-network

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - quickdelivery-network

networks:
  quickdelivery-network:
    driver: bridge

volumes:
  postgres-data: 