name: PlantUML Diagrams

on:
  push:
    branches:
      - main
    paths:
      - 'lab-works/sprint-3/**'
  pull_request:
    branches:
      - main
    paths:
      - 'lab-works/sprint-3/**'

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install PlantUML
      run: sudo apt-get install plantuml

    - name: Generate Diagrams
      run: |
        plantuml sprint-3/lab1-plantuml-c4/diagrams/context/*.puml
        plantuml sprint-3/lab1-plantuml-c4/diagrams/container/*.puml
        plantuml sprint-3/lab1-plantuml-c4/diagrams/component/*.puml
        plantuml sprint-3/lab1-plantuml-c4/diagrams/code/*.puml

    - name: Commit Diagrams
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add sprint-3/lab1-plantuml-c4/diagrams/**/*.png
        git commit -m "Automated diagram generation"
        git push origin main
      if: success()
    permissions:
      contents: write
